---
title: "HW 03"
author: "Cat Xia"
format:
  html:
    embed-resources: true
toc: true
---

## 1 - Du Bois challenge.

```{r loading packages}
#| label: loading packages

if (!require("pacman"))
  install.packages("pacman")

pacman::p_load(tidyverse, here, glue, scales, janitor, forcats)

ggplot2::theme_set(ggplot2::theme_minimal())
options(width = 65)
knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = 0.618,
  fig.retina = 3,
  fig.align = "center",
  api = 300
)

```

```{r load data}
#| label: load data

income <- read.csv(here("data", "income.csv"))
income <- clean_names(income)
glimpse(income)
```
```{r du bois data wrangling}
#| label: du bois data wrangling

#pivots the table so that it creates two new columns, one for spending type and one for the amount
income_clean <- income|>
  pivot_longer(cols = -c(class, average_income), names_to = "spending_type", values_to = "amount")

income_clean$class <- fct_relevel(
  income_clean$class,
  "$1000 AND OVER", 
  "$750-1000", 
  "$500-750", 
  "$400-500", 
  "$300-400", 
  "$200-300", 
  "$100-200"
)

income_clean$spending_type <- fct_relevel(
  income_clean$spending_type,
  "other", "tax", "clothes", "food", "rent"
)
```


```{r du bois recreation}
#| label: du bois recreation

income_clean |>
  ggplot(aes(x = class, y = amount, fill = spending_type, order = spending_type)) +
  geom_bar(stat = "identity", position = "fill") +
  coord_flip() +
  scale_fill_manual(values = c("grey","lightblue","pink", "#966FD6", "grey10")) 

```


## 2 - COVID survey - interpret

```{r}
#| label: label-me-2

```

## 3 - COVID survey - reconstruct

```{r Q3 load data}
#| label: load data

covid <- read.csv(here("data", "covid-survey.csv"), skip = 1)
dim(covid)
```
```{r Q3 Data cleaning}
#| label: Q3 Data Cleaning

covid <- clean_names(covid)
covid <- covid |>
  filter(if_any(-1, ~ !is.na(.))) #*
dim(covid)
```
* Code after consulting with https://www.tidyverse.org/blog/2021/02/dplyr-1-0-4-if-any/. -1 from my own code, '~ !is.na(.)' formatting consulted from AI after multiple bug issues.

```{r Q3 renaming variables}
#| label: renaming variables

covid_survey <- covid |>
  mutate(
    "exp_already_vax" = if_else(exp_already_vax == 0, "No", "Yes"),
    "exp_flu_vax" = if_else(exp_flu_vax == 0, "No", "Yes"),
    "exp_profession" = if_else(exp_profession == 0, "Medical", "Nursing"),
    "exp_gender" = case_when(
      exp_gender == 0 ~ "Male",
      exp_gender == 1 ~ "Female",
      exp_gender == 3 ~ "Non-binary third gender",
      exp_gender == 4 ~ "Prefer not to say",
    ),
    "exp_race" = case_when(
      exp_race == 1 ~ "American Indian/Alaskan Native",
      exp_race == 2 ~ "Asian",
      exp_race == 3 ~ "Black/African American",
      exp_race == 4 ~ "Native Hawaiian/Other Pacific Islander",
      exp_race == 5 ~ "White"
    ),
    "exp_ethnicity" = if_else(exp_ethnicity == 1, "Hispanic/Latino", "Non-Hispanic/Non-Latino"),
    "exp_age_bin" = case_when(
      exp_age_bin == 0 ~ "<20",
      exp_age_bin == 20 ~ "21-25",
      exp_age_bin == 25 ~ "26-30",
      exp_age_bin == 30 ~ ">30"
    )
  )
dim(covid_survey)
```

```{r pivot longer Q3 code given}
#| label: pivot longer Q3 code given

covid_survey_longer <- covid_survey |>
  pivot_longer(
    cols = starts_with("exp_"),
    names_to = "explanatory",
    values_to = "explanatory_value"
  ) |>
  filter(!is.na(explanatory_value)) |>
  pivot_longer(
    cols = starts_with("resp_"),
    names_to = "response",
    values_to = "response_value"
  )
covid_survey_longer
```


## 4 - COVID survey - re-reconstruct

## 5 - COVID survey - another view
